### PR TITLE
Angular best practices restructuring

### PR DESCRIPTION
**Pull request by robman87**
Started work on following the Angular style guide to improve the development experience.
https://github.com/johnpapa/angular-styleguide/tree/master/a1

### CODE REVIEW

**Comment by ritz078** [comment]
@robman87 I think houndci can be disabled.

**Comment by robman87** [comment]
Maybe an .editorconfig file could be a good idea, to make the code style, indentation etc more consistent?

**Comment by ritz078** [comment]
yes that's a nice idea.

**Comment by ritz078** [comment]
How about we use some boilerplate that has all the build scripts and lintings done already ?

**Comment by robman87** [comment]
Sure, I'm more used to grunt not npm scripts though.

**Pull request merged**
